# Generated by Django 3.0 on 2021-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recfaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
        migrations.AddField(
            model_name='person',
            name='imageEnc',
            field=models.CharField(default='None', max_length=1024),
        ),
        migrations.AddField(
            model_name='person',
            name='imagePath',
            field=models.ImageField(default='None', upload_to='facesImages/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.SmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
