# Generated by Django 3.0 on 2021-02-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recfaces', '0002_auto_20210212_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imageEnc',
            field=models.BinaryField(default=None, max_length=1024),
        ),
    ]
