# Generated by Django 3.0 on 2021-02-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recfaces', '0003_auto_20210212_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='imageEnc',
            new_name='binImg',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='imagePath',
            new_name='imgPath',
        ),
    ]
