# Generated by Django 3.0 on 2021-02-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recfaces', '0004_auto_20210213_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='fio',
        ),
    ]
