# Generated by Django 3.1.7 on 2021-02-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recfaces', '0005_auto_20210213_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imgPath',
            field=models.ImageField(default='None', upload_to='tmp'),
        ),
    ]
