# Generated by Django 3.1.7 on 2021-02-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recfaces', '0007_auto_20210227_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='binImg',
        ),
    ]
