# Generated by Django 3.1.7 on 2021-02-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recfaces', '0008_remove_person_binimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imgPath',
            field=models.ImageField(default='None', max_length=200, upload_to='tmp'),
        ),
    ]
