# Generated by Django 3.1.7 on 2021-02-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recfaces', '0009_auto_20210228_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='binImg',
            field=models.BinaryField(default=None, max_length=2048),
        ),
    ]
