# Generated by Django 3.1.7 on 2021-03-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recfaces', '0010_person_binimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='idSource',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('?', '?'), ('M', 'Male'), ('F', 'Female')], default='?', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='imgPath',
            field=models.ImageField(default='None', max_length=200, upload_to=''),
        ),
    ]
